# Site settings
title: Bas's Profile
email: aalders.bas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning working with Git
baseurl: "/patchwork-gh-pages-24"
url: "http://bas-aalders.github.io"
twitter_username: basaalders
github_username:  bas-aalders
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
